# the list of websites to try to ping, each separated by a comma:
hosts=wholefoods.com, amazon.com
# the number of threads to use when running Mapping:
threads=6
# the name of the JSON file to write no (do not inclde .json in the entry):
filename=results
