# the location of the authentication log to parse
log-location=auth.log
# the minimum number of failed attempts required to carry out an IP block
num-failed-attempts-required=5
# the name of the jail to be created should automatic fail2ban blocking occur.\
target-jail=sshd
