# the location of the firewall log that will be parsed
log-location=ufw.log
# the minimum number of blocked events against an IP required to add a firewall rule blocking its traffic
num-blocks-required=100
# a list of comma-separated IP address from which all traffic should be unconditionally accepted
whitelist=
