# the port range to scan over, with the starting port, separated from the end port by a comma
port-range=1,1024
# the amount of time to try to connect to a port on an IP address:
timeout=0.5
# the total number of threads to run on this program
threads=30
# the comma-separated IP address on which to perform a port scan.
ips=192.168.1.1,192.168.1.159
