# the IP address of the router to use in ping tests
router-ip=192.168.1.1
# the IP address of the DNS to use in ping and lookup tests
dns-ip=192.168.1.1
# the website to use in HTTP request tests
test-website=amazon.com
# the name of the JSON file to write results to (omit '.json', include only name)
log-name=results
# the amount of time in seconds to wait before terminating a ping or connection attempt
timeout=5
