# the ports (comma separated!) that Microbait will operate on and accept incoming connections from
ports=22,443,80
# the banner that will be sent over from Microbait to the connecting user (change the default values!)
services=SSH,HTTP,WEB
# the total number of bytes that the connection can receive before terminating to prevent receiving unlimited data.
max-bytes=65536
