# the port that Microbait will operate on and accept incoming connections from
port=2222
# the banner that will be sent over from Microbait to the connecting user
service=SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
# the total number of bytes that the connection can receive before terminating to prevent receiving unlimited data
max-bytes=65536
